package jenkinfiles

pipeline {
    agent any

    environment {
        // путь к Java на localhost
        JAVA_HOME = 'C:\\Program Files\\Java\\jdk-17'
        BASE_URL = 'https://www.championat.com/'
        BROWSER = 'chrome'
    }

    triggers {
        pollSCM('H/5 * * * *') // Проверять изменения каждые 5 минут
    }

    stages {
        stage('Подготовка') {
            steps {
                echo 'Клонирование репозитория и настройка окружения...'
                cleanWs()

                // Для локального тестирования можно использовать SSH URL
                git(
                        branch: 'master',
                        //url: 'git@github.com:AlexanderSchulga/TestChampionatJenkins.git',
                        url: 'https://github.com/AlexanderSchulga/TestChampionatJenkins.git',
                        credentialsId: 'github-credentials'
                )
            }
        }

        stage('Сборка') {
            steps {
                echo 'Сборка проекта...'
                sh 'mvn clean compile'
            }
        }

        stage('Запуск тестов') {
            steps {
                echo 'Запуск UI-тестов с Selenide и Cucumber...'

                // необходимые переменные окружения
                script {
                    // Для Selenide обычно не требуется явно указывать путь к драйверу,
                    // так как Selenide автоматически управляет драйверами

                    // Запуск тестов через Maven
                    bat 'mvn clean install'

                    // Если нужно передать параметры, для разных окружений:
                    // к примеру, в headless-режиме (запуск без gui, в командной строке)

                    // sh 'mvn clean test -Dselenide.browser=chrome -Dcucumber.filter.tags="@smoke"'
                }
            }

            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                    // Архивирование результатов
                    archiveArtifacts artifacts: '**/target/surefire-reports/*.*', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline завершен. Результат: ${currentBuild.result}"

            // Для локального тестирования уведомление в консоль
            script {
                if (currentBuild.result == 'SUCCESS') {
                    echo 'Тесты прошли успешно!'
                } else {
                    echo 'Обнаружены ошибки в тестах!'
                }
            }
        }
    }
}
